collections:
  seminars:
    output: true
  projects:
    output: true
  events:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default2"
      container: true
  -
    scope:
      path: ""
      type: "seminars"
    values:
      layout: "seminars"

future: true
